{
  "instructions": [
    "let parseAssertElemProp = await page.$(\"a\");\nif (parseAssertElemProp === null) { throw '\"a\" not found'; }\nawait page.evaluate(e => {\n    const nonMatchingProps = [];\n    const parseAssertElemPropDict = {};\n    const undefProps = [\"a\"];\n    for (const prop of undefProps) {\n        if (e[prop] !== undefined) {\n            continue;\n        }\n    nonMatchingProps.push(\"Property named `\" + prop + \"` doesn't exist\");\n    }\n    for (const [parseAssertElemPropKey, parseAssertElemPropValue] of Object.entries(parseAssertElemPropDict)) {\n        if (e[parseAssertElemPropKey] === undefined) {\n            continue;\n        }\n        if (String(e[parseAssertElemPropKey]).startsWith(parseAssertElemPropValue)) {\n            nonMatchingProps.push(\"assert didn't fail for property `\" + parseAssertElemPropKey + '` (for STARTS_WITH check)');\n        }\n    }\n    if (nonMatchingProps.length !== 0) {\n        const props = nonMatchingProps.join(\", \");\n        throw \"The following errors happened (for selector `a`): [\" + props + \"]\";\n    }\n}, parseAssertElemProp);"
  ],
  "wait": false,
  "warnings": [
    "`STARTS_WITH` is present more than once in the third argument array",
    "Special checks (STARTS_WITH) will be ignored for `null`"
  ],
  "checkResult": true
}
